---
- name: Add users
  hosts: nodes
  vars_files:
    - vars/users
  become: true
  tasks:
  - name: Add users
    user:
      name: "{{ item.key }}"
      comment: "{{ item.value.email }}"
      home: "{{ item.value.home }}"
      password: "{{ item.value.password | password_hash('sha512')}}"
      update_password: on_create
      state: present
    with_dict: "{{ users }}"
    no_log: yes
...
