---
# vars file for vsftpd-role
path_upload: /var/ftp/pub/upload
options:
  write_enable: "YES"
  anonymous_enable: "YES"
  no_anon_password: "YES"
  anon_upload_enable: "YES"
  anon_mkdir_write_enable: "YES"
  anon_other_write_enable: "YES"
  anon_root: /var/ftp/pub
  anon_umask: '022'
